version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: vomo_production_managament
      POSTGRES_USER: vomo_admin
      POSTGRES_PASSWORD: vomo_admin_123@#$
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backup:/app/backup  # Backup inside the project root folder

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@vomo.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - postgres

  backup:
    image: postgres:15
    container_name: postgres_backup
    restart: always
    volumes:
      - ./backup:/app/backup  # Backup stored inside project root
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: vomo_production_managament
      POSTGRES_USER: vomo_admin
      POSTGRES_PASSWORD: vomo_admin_123@#$
    entrypoint: ["/bin/sh", "-c", "while true; do sleep 86400; pg_dump -h $POSTGRES_HOST -U $POSTGRES_USER -F c -b -v -f /app/backup/db_backup_$(date +%F).dump $POSTGRES_DB; done"]
    depends_on:
      - postgres

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.0
    container_name: kibana
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_PUBLICBASEURL=http://localhost:5601
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic

volumes:
  postgres_data:
    driver: local
  elasticsearch_data:
    driver: local

networks:
  elastic:
    driver: bridge
